version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres17
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: D7p$3r!uVg9q@1ZwTb8&
      POSTGRES_DB: establishment_management
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data